# Generated by Django 5.1.15 on 2026-06-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='corequisitos',
            field=models.ManyToManyField(blank=True, related_name='materias_corequisito_de', to='pensums.materia', verbose_name='Co-requisitos'),
        ),
        migrations.AddField(
            model_name='materia',
            name='prerrequisitos',
            field=models.ManyToManyField(blank=True, related_name='materias_prerrequisito_de', to='pensums.materia', verbose_name='Pre-requisitos'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.CharField(choices=[('1', '1° Cuatrimestre'), ('2', '2° Cuatrimestre'), ('3', '3° Cuatrimestre'), ('4', '4° Cuatrimestre'), ('5', '5° Cuatrimestre'), ('6', '6° Cuatrimestre'), ('7', '7° Cuatrimestre'), ('8', '8° Cuatrimestre'), ('9', '9° Cuatrimestre'), ('10', '10° Cuatrimestre'), ('11', '11° Cuatrimestre'), ('12', '12° Cuatrimestre')], max_length=2),
        ),
    ]
