# Generated by Django 5.1.15 on 2026-06-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensums', '0002_materia_corequisitos_materia_prerrequisitos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recinto',
            old_name='imagen',
            new_name='portada',
        ),
        migrations.AlterField(
            model_name='recinto',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='recintos/portadas/', verbose_name='Portada'),
        ),
    ]
